# coding: utf-8

ESP = 0.0001

SPETIAL_TAGS = [
    u'big',
    u'dt',
    u'li',
    u'a',
    u'title',
    u'b',
    u'thead',
    u'h1',
    u'h2',
    u'h3',
    u'h4',
    u'h5',
    u'h6',
    u'style',
    u'header',
    u'strong',
    u'ol',
    u'small',
    u'section',
    u'i',
    u'em',
    u'abbr',
    u'cite',
    u'ins',
    u'dfn',
    u'strike',
    u'pre',
    u'code',
    u'tt',
    u'blockquote',
    u'font',
]

COMMON_TAGS = [u'noindex', u'code', u'aside', None, u'font', u'noscript', u'style',
               u'img', u'title', u'tt', u'tr', u'param', u'li', u'tfoot', u'th',
               u'input', u'td', u'dl', u'blockquote', u'fieldset', u'big', u'dd',
               u'nobr', u'abbr', u'dt', u'marquee', u'button', u'p', u'small',
               u'div', u'em', u'hgroup', u'meta', u'index', u'section', u'label',
               u'sup', u'body', u'acronym', u'base', u'br', u'address', u'article',
               u'strong', u'legend', u'ol', u'area', u'nofollow', u'caption',
               u'col', u'h2', u'h3', u'image', u'h1', u'h6', u'h4', u'h5',
               u'header', u'table', u'select', u'span', u'script', u'dfn', u'cite',
               u'thead', u'head', u'option', u'form', u'hr', u'link', u'b',
               u'colgroup', u'ul', u'del', u'iframe', u'embed', u'pre', u'ins',
               'tag', u'tbody', u'html', u'nav', u'map', u'object',
               u'st1:metricconverter', u'a', u'center', u'textarea', u'footer',
               u'i', u'u', u'time', u'left']

RUS_UNICODE_RANGE = "\u0400-\u0500"

RUS_STOP_WORDS = [
    u'и',
    u'в',
    u'во',
    u'не',
    u'что',
    u'он',
    u'на',
    u'я',
    u'с',
    u'со',
    u'как',
    u'а',
    u'то',
    u'все',
    u'она',
    u'так',
    u'его',
    u'но',
    u'да',
    u'ты',
    u'к',
    u'у',
    u'же',
    u'вы',
    u'за',
    u'бы',
    u'по',
    u'только',
    u'ее',
    u'мне',
    u'было',
    u'вот',
    u'от',
    u'меня',
    u'еще',
    u'нет',
    u'о',
    u'из',
    u'ему',
    u'теперь',
    u'когда',
    u'даже',
    u'ну',
    u'вдруг',
    u'ли',
    u'если',
    u'уже',
    u'или',
    u'ни',
    u'быть',
    u'был',
    u'него',
    u'до',
    u'вас',
    u'нибудь',
    u'опять',
    u'уж',
    u'вам',
    u'ведь',
    u'там',
    u'потом',
    u'себя',
    u'ничего',
    u'ей',
    u'может',
    u'они',
    u'тут',
    u'где',
    u'есть',
    u'надо',
    u'ней',
    u'для',
    u'мы',
    u'тебя',
    u'их',
    u'чем',
    u'была',
    u'сам',
    u'чтоб',
    u'без',
    u'будто',
    u'чего',
    u'раз',
    u'тоже',
    u'себе',
    u'под',
    u'будет',
    u'ж',
    u'тогда',
    u'кто',
    u'этот',
    u'того',
    u'потому',
    u'этого',
    u'какой',
    u'совсем',
    u'ним',
    u'здесь',
    u'этом',
    u'один',
    u'почти',
    u'мой',
    u'тем',
    u'чтобы',
    u'нее',
    u'сейчас',
    u'были',
    u'куда',
    u'зачем',
    u'всех',
    u'никогда',
    u'можно',
    u'при',
    u'наконец',
    u'два',
    u'об',
    u'другой',
    u'хоть',
    u'после',
    u'над',
    u'больше',
    u'тот',
    u'через',
    u'эти',
    u'нас',
    u'про',
    u'всего',
    u'них',
    u'какая',
    u'много',
    u'разве',
    u'три',
    u'эту',
    u'моя',
    u'впрочем',
    u'хорошо',
    u'свою',
    u'этой',
    u'перед',
    u'иногда',
    u'лучше',
    u'чуть',
    u'том',
    u'нельзя',
    u'такой',
    u'им',
    u'более',
    u'всегда',
    u'конечно',
    u'всю',
    u'между',
]
